# Uncomment the next line to define a global platform for your project
# platform :macos, '10.11'

target 'PROJECT_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PROJECT_Example

end
